### PR TITLE
Fix date array bug in EndNote formats

### LINKED ISSUE #52: Bug: EndNote date arrays contain four items instead of three
## Summary

Some EndNote articles with unusually formatted dates will generate a date array field with an extra fourth items when there should only be three. When these articles are uploaded into Rayyan, the following error is raised:

    Error: wrong number of arguments (given 4, expected 1..3)

## Details

This bug seems to occur when the date in the `%8` field contains a range, e.g.,

    %D 2008
    %8 Nov 5-11

In such cases, Ruby's date parsing will interpret the second day in the `%8` range as a negative year ("-0011") and the `#date_array` method in the plugin will split the string returned on the `-` sign, returning the array `["", "0011", "11", "5"]`. Removing the `-` in the regex used to split the date is a simple way to fix the bug whilst maintaining functionality for other known date formats

### PR DESCRIPTION
**Pull request by kohrVid**
Closes #52 

EndNote documents with the following date values will produce a date array with four items when uploaded instead of three:

    %D 2008
    %8 Nov 5-11

This is because the second day in the `%8` range is interpreted as a negative year ("-0011") and the `#date_array` method splits on the `-` sign, returning the array `["", "0011", "11", "5"]` for the `%8` date. Removing the `-` in the regex used to split the date is a simple way to fix the bug whilst maintaining functionality for other known date formats.

As well as updating the regex used, this PR moves some of the logic used to create the date array into a separate class with a method that both the EndNote and Refman plugins can call.

### CODE REVIEW

File: lib/rayyan-formats-plugins/date_formatter.rb [hunk 1]
```diff
@@ -0,0 +1,25 @@
...
+      date_arr = Date.parse(date).strftime("%Y %-m %-d").split(/[\/\s]/) rescue date&.split(/\D+/)&.map do |i|
+        i.gsub(/^#{@start_regex}/, "")
+      end
+
+      # Remove incorrect year or day if missing from the original string
+      date_arr[0] = "" if date_arr[0] && !date.include?(date_arr[0])
+      date_arr.pop if date_arr[2] && !date.include?(date_arr[2])
+
+      date_arr
+    end
```
Comment (hammady) [inline lib/rayyan-formats-plugins/date_formatter.rb:23]: Would it be useful as a defensive approach to check for the length of the array before returning and make sure it is less than 4? In this case, I believe we should just return an empty array. What do you think?

Comment (kohrVid) [reply lib/rayyan-formats-plugins/date_formatter.rb:25]: I think that makes sense. I've updated the PR with an `if` statement that will check the length going forwards

**Review by hammady — APPROVED** [review]
